consumer_token: 'blahblahblah'
consumer_secret: 'blahblahblah'
access_token: 'blahblahblah'
access_secret: 'blahblahblah'

retweet_words:
- '@IchBinVierzehn'
- 'trailerpark'
- 'overknees'
- 'babobus'
- 'longboardtour'
- '257er'

forbidden_words:
- 'schlampe'
- 'fick'
- 'sex'
- 'twitter'
- 'schwanz'
- 'schwänze'
- 'fetish'
- 'porn'
- 'geil'
- 'geile'
- 'ich habe ein video zu einer'
- 'restposten'
- 'herbst'
- 'peitsche'
- 'lack'
- 'lutze'
- 'glove'
- 'butt'
- 'muschi'
- 'fotze'
- 'vagina'
- 'cheese'
- 'etzela'
- 'drachenlord'
- 'Schlaf gut'
- 'RT'
- 'fashion'
- 'spritz'
- 'abspritzen'
- 'mass-home'
- 'arschglotzsteuer'
- 'busen-maus'
- 'S****z'
- 'bowknots'
- 'amateur-boots'
- 'overkneeboots'
- 'bitch'
- 'fucked'
- 'new'
- 'fuckin'
- 'story'
- 'stiefel'
- 'leder'
- 'stiletto'
