consumer_token: 'blahblahblah'
consumer_secret: 'blahblahblah'
access_token: 'blahblahblah'
access_secret: 'blahblahblah'

redis_host: 'localhost'
redis_port: 6379
redis_dbnr: 14

retweet_words:
- '@IchBinVierzehn'
- 'trailerpark'
- 'overknees'
- 'babobus'
- 'longboardtour'
- '257er'
- 'tattookette'
- 'tattooketten'

forbidden_words:
- 'schlampe'
- 'fick'
- 'sex'
- 'twitter'
- 'schwanz'
- 'schwänze'
- 'fetish'
- 'porn'
- 'geil'
- 'geile'
- 'ich habe ein video zu einer'
- 'restposten'
- 'herbst'
- 'peitsche'
- 'lack'
- 'lutze'
- 'glove'
- 'butt'
- 'muschi'
- 'fotze'
- 'vagina'
- 'cheese'
- 'etzela'
- 'drachenlord'
- 'Schlaf gut'
- 'fashion'
- 'spritz'
- 'abspritzen'
- 'mass-home'
- 'arschglotzsteuer'
- 'busen-maus'
- 'S****z'
- 'bowknots'
- 'amateur-boots'
- 'overkneeboots'
- 'bitch'
- 'fucked'
- 'new'
- 'fuckin'
- 'story'
- 'stiefel'
- 'leder'
- 'stiletto'
- 'shoppen'
- 'stockings'
- 'size'

forbidden_apps:
- 'IFTTT'
- 'WordPress.com'
- 'Instagram'
- 'Google'
